[package]
name = "sqruff-sqlinference"
description = "A high-speed SQL linter inference library."
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sqruff-parser-tree = { workspace = true }
sqruff-parser-core.workspace = true

[dev-dependencies]
sqruff-lib-dialects = { workspace = true }
