[package]
name = "sqruff-sqlinference"
description = "A high-speed SQL linter inference library."
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sqruff-lib-core = { workspace = true }
hashbrown.workspace = true

[dev-dependencies]
sqruff-lib-dialects = { workspace = true }
