on: [pull_request]
name: benchmark pull requests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
jobs:
  benchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v5
      - uses: boa-dev/criterion-compare-action@59f4d964c5f19d7f13d36f5c0944b18ce6652cb0
        with:
          branchName: ${{ github.base_ref }}
          package: "sqruff-lib"
